retargeting:
  type: DexPilot
  urdf_path: orca_hand/orcahand_right_glb.urdf

  # Target refers to the retargeting target, which is the robot hand
  wrist_link_name: "right_palm"
  finger_tip_link_names: [ "right_thumb_fingertip", "right_index_fingertip", "right_middle_fingertip", "right_ring_fingertip", "right_pinky_fingertip" ]
  scaling_factor: 1.0

  # A smaller alpha means stronger filtering, i.e. more smooth but also larger latency
  low_pass_alpha: 0.2 